language: generic
sudo: required
services: docker
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    # via the "travis encrypt" command using the project repo's public key
    - secure: "r6JisGshiAE90hYmSSqSoLVC8Pa1s0Q+GgArvwnqikvgnU18lWjHR8mC0UlDb6VeYshgWDeGpVk4Wg9f/whMMTQIBIqTrg5bHTfUtrFjVwp5OUqCDTtO6EoDmqopJyRDMFWELVhgNBaE74A54vqK61a03gsR1vCu50sUfq+MjnY="
    - COVERITY_SCAN_SCRIPT_URL="https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh"
    - COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG"
    - COVERITY_SCAN_BRANCH_PATTERN="coverity_scan"
    - COVERITY_SCAN_NOTIFICATION_EMAIL="guillem@debian.org"
    - COVERITY_SCAN_BUILD_COMMAND="make"
    - COVERITY_SCAN_BUILD_COMMAND_PREPEND="autoreconf -f -i && ./configure"
before_install:
  - cp -a debian/ .travis/
  - docker build -t dpkg/debian:stretch .travis/
  - env | grep -E "TRAVIS|COV|FLAGS" >.travis/cov-env
script:
  - docker run --env-file .travis/cov-env
    -v `pwd`:/build dpkg/debian:stretch
    sh -c "curl -s $COVERITY_SCAN_SCRIPT_URL | bash || true"
